[global]
  e2dsa                          # enable file indexing and filesystem scanning
  e2ts                           # enable multimedia indexing
  ansi                           # enable colors in log messages (both in logfiles and stdout)
  hist: /cfg/hists/              # place caches seperate from filesystem
  # q, lo: /cfg/log/%Y-%m%d.log  # log to file instead of docker
  # p: 3939                      # listen on another port
  # ipa: 10.89.                  # only allow connections from 10.89.*
  # ipa: 172.16.4.0/23           # ...or only 172.16.4.* and 172.16.5.*
  # ipa: lan                     # ...or allow LAN only; reject internet IPs
  df: 16                         # stop accepting uploads if less than 16 GB free disk space
  # ver                          # show copyparty version in the controlpanel
  # grid                         # show thumbnails/grid-view by default
  # theme: 2                     # monokai
  name: olsonsky                 # change the server-name that's displayed in the browser
  # stats, nos-dup               # enable the prometheus endpoint, but disable the dupes counter (too slow)
  no-robots, force-js            # make it harder for search engines to read your server
  shr: /public                   # enable tmp link sharing
  rproxy: 1
  xff-hdr: x-forwarded-for
  xff-src: lan

[accounts]
  {{ COPYPARTY_USER_JTO }}
  {{ COPYPARTY_USER_ANO }}

[groups]
  admins: thenome,audra  # create a group, comma sep

[/shared]                  # create a volume at "/" (the webroot), which will
  /w/shared                # share /w (the docker data volume)
  accs:                    #
    # r: *                 # everyone gets read-write access, but
    A: @admins             # the user "ed" gets read-write-move-delete-admin
  flags:                   #
    fk: 4                  #
