services:
  # do not delete data
  mc3:
    container_name: mc3
    image: docker.io/itzg/minecraft-server:latest
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "25567:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - ${VOLUME_DIR}/mc3:/data
    labels:
      - 'portical.upnp.forward=25567:25567/tcp'
      - 'podlab.dns.update=olsonsky.com a mc3 auto|olsonsky.com srv _minecraft._tcp.mc3 mc3 25567'
      - 'podlab.html.set=Minecraft Version: 1.21.11 | Modpack: NA | Mods: NA | Port: 25567 | Description: Simple minecraft world no mods. Joint this if in doubt.'
