networks:
  backend:
    driver: bridge

services:

  haproxy:
    image: docker.io/haproxy:alpine
    container_name: haproxy
    user: root
    network_mode: host
    user: "0:0"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro,Z
    restart: always
    labels:
      - 'portical.upnp.forward=443:10443/all|80:10080/all'

  traefik:
    image: docker.io/traefik
    container_name: traefik
    # network_mode: host
    # network_mode: pasta
    restart: always
    ports:
      - "8000:80"
      - "8443:443"
      - "8080:8080"
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ${VOLUME_DIR}/traefik_acme:/etc/traefik/acme
      - ${VOLUME_DIR}/traefik_data/:/data
    labels:
      # - 'portical.upnp.forward=443:8443/all|80:8000/all'
      - 'podlab.dns.update=olsonsky.com a @ auto'
    networks:
      - backend

  nginxstatic:
    image: docker.io/flashspys/nginx-static
    container_name: nginxstatic
    restart: always
    ports:
      - 8081:80
    volumes: 
      - ${VOLUME_DIR}/html:/static:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginxstatic.rule=Host(`minecraft.olsonsky.com`)"
      - 'podlab.dns.update=olsonsky.com a minecraft auto'
    networks:
      - backend

  copyparty:
    # Before running you must template the config files with users since no user via env option exists
    # pipx install jinja2-cli
    # jinja2 -f env copyparty/copyparty.conf .env > .env.copyparty.conf
    image: docker.io/copyparty/ac:latest
    container_name: copyparty
    ports:
      - 3923:3923 
    volumes:
      - /shared:/w/shared:z
      - ${VOLUME_DIR}/copyparty_cfg:/cfg
      - .env.copyparty.conf:/cfg/copyparty.conf:ro
    # restart: always
    environment:
      # LD_PRELOAD: /usr/lib/libmimalloc-secure.so.NOPE
      # enable mimalloc by replacing "NOPE" with "2" for a nice speed-boost (will use twice as much ram)
      PYTHONUNBUFFERED: 1
      # ensures log-messages are not delayed (but can reduce speed a tiny bit)
    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    healthcheck:
      # hide it from logs with "/._" so it matches the default --lf-url filter 
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.copyparty.rule=Host(`share.olsonsky.com`)"
      - 'podlab.dns.update=olsonsky.com a share auto'
    networks:
      - backend

  podlab:
    image: thenomemac/podlab:latest
    container_name: podlab
    restart: always
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    environment:
      - DO_AUTH_TOKEN=${DO_AUTH_TOKEN}
    network_mode: host
